//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_Companies
    {
        public int Address_CompanyId { get; set; }
        public int AddressId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
    }
}
