//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogue_CompanyCreditInfo
    {
        public int Catalogue_CompanyCreditInfoId { get; set; }
        public int CatalogueID { get; set; }
        public int CompanyCreditInfoID { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual CompanyCreditInfo CompanyCreditInfo { get; set; }
    }
}
