//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogues_Colours
    {
        public int CatalogueColourId { get; set; }
        public Nullable<int> CatalogueId { get; set; }
        public Nullable<int> ColourId { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Colour Colour { get; set; }
    }
}
