//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.CategoryMatchingFeatures = new HashSet<CategoryMatchingFeature>();
            this.Discounts = new HashSet<Discount>();
            this.ProductServices = new HashSet<ProductService>();
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<int> CategoryOrder { get; set; }
        public int CatalogueID { get; set; }
        public Nullable<int> CategoryGroupId { get; set; }
        public bool HasMatchingFeatures { get; set; }
        public bool BespokeProductOrService { get; set; }
        public bool DoorAndDrawerFront { get; set; }
        public bool FrontMatching { get; set; }
        public bool UnitMatching { get; set; }
        public bool WorktopPanel { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual CategoryGroup CategoryGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryMatchingFeature> CategoryMatchingFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductService> ProductServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
