//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Catalogues
    {
        public int Company_CatalogueId { get; set; }
        public int CompanyId { get; set; }
        public int CatalogueId { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Catalogue Catalogue1 { get; set; }
    }
}
