//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCreditInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyCreditInfo()
        {
            this.Catalogue_CompanyCreditInfo = new HashSet<Catalogue_CompanyCreditInfo>();
        }
    
        public int CompanyCreditInfoID { get; set; }
        public int CompanyID { get; set; }
        public int CatalogueID { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> RemainingLimit { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogue_CompanyCreditInfo> Catalogue_CompanyCreditInfo { get; set; }
        public virtual Catalogue Catalogue { get; set; }
        public virtual Company Company { get; set; }
    }
}
