//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCharge
    {
        public int DeliveryChargesId { get; set; }
        public int CountyId { get; set; }
        public int CatalogueId { get; set; }
        public Nullable<decimal> DeliveryCharge1 { get; set; }
        public Nullable<decimal> FreeOfCharge { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual County County { get; set; }
    }
}
