//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoorStyle()
        {
            this.DoorStyleImages = new HashSet<DoorStyleImage>();
            this.DoorStyleTags = new HashSet<DoorStyleTag>();
            this.Order_Products = new HashSet<Order_Products>();
            this.Orders = new HashSet<Order>();
            this.Quote_DoorStyles = new HashSet<Quote_DoorStyles>();
            this.Quote_Products = new HashSet<Quote_Products>();
            this.Quotes = new HashSet<Quote>();
            this.RangeGroup_DoorStyle = new HashSet<RangeGroup_DoorStyle>();
        }
    
        public int DoorStyleID { get; set; }
        public string Abbreviation { get; set; }
        public string DoorStyle1 { get; set; }
        public int PriceGroup { get; set; }
        public string AlternateAbbreviation { get; set; }
        public string Description { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public bool IsNew { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> HasImage { get; set; }
    
        public virtual PriceGroup PriceGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoorStyleImage> DoorStyleImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoorStyleTag> DoorStyleTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Products> Order_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_DoorStyles> Quote_DoorStyles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_Products> Quote_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RangeGroup_DoorStyle> RangeGroup_DoorStyle { get; set; }
    }
}
