//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Products = new HashSet<Order_Products>();
            this.Order_ProductServices = new HashSet<Order_ProductServices>();
            this.OrderAddresses = new HashSet<OrderAddress>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public int OrderId { get; set; }
        public string OrderRef { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CustomerId { get; set; }
        public int QuoteId { get; set; }
        public int CompanyId { get; set; }
        public int TrendUserId { get; set; }
        public int VatRateID { get; set; }
        public int StatusID { get; set; }
        public int PrimaryDoorStyle { get; set; }
        public Nullable<int> DrawerBoxColour { get; set; }
        public int PaymentMethod { get; set; }
        public Nullable<decimal> NetGrossTotal { get; set; }
        public Nullable<decimal> CostVatTotal { get; set; }
        public Nullable<decimal> NetCostTotal { get; set; }
        public Nullable<decimal> SalesGrossTotal { get; set; }
        public Nullable<decimal> SalesVatTotal { get; set; }
        public Nullable<decimal> NetSalesTotal { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public int DeliveryMethod { get; set; }
        public System.DateTime DeliveryDateWc { get; set; }
        public string DeliveryNotes { get; set; }
        public int Catalogue { get; set; }
        public int PrimaryCabinetColour { get; set; }
        public bool AddVAT { get; set; }
        public bool Archived { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool CustomerPanelVisible { get; set; }
        public bool ContactPanelVisible { get; set; }
        public Nullable<bool> UseDelivery { get; set; }
        public Nullable<int> AddressIDToUse { get; set; }
        public bool DeliveryDetailsConfirmed { get; set; }
        public bool TermsConfirmed { get; set; }
        public bool ReadOnly { get; set; }
        public Nullable<int> PrimaryHandleStyle { get; set; }
        public Nullable<decimal> CurrencySurcharge { get; set; }
    
        public virtual Catalogue Catalogue1 { get; set; }
        public virtual Colour Colour { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryMethod DeliveryMethod1 { get; set; }
        public virtual DoorStyle DoorStyle { get; set; }
        public virtual DrawerBox DrawerBox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Products> Order_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_ProductServices> Order_ProductServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAddress> OrderAddresses { get; set; }
        public virtual OrderQuoteStatu OrderQuoteStatu { get; set; }
        public virtual PaymentMethod PaymentMethod1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual TrendUser TrendUser { get; set; }
        public virtual VatRate VatRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
