//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int ProductPriceID { get; set; }
        public int ProductID { get; set; }
        public int PriceGroupID { get; set; }
        public decimal Price { get; set; }
    
        public virtual PriceGroup PriceGroup { get; set; }
        public virtual Product Product { get; set; }
    }
}
