//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFavourite
    {
        public int ProductFavouriteId { get; set; }
        public int ProductId { get; set; }
        public int TrendUserId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TrendUser TrendUser { get; set; }
    }
}
