//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductService()
        {
            this.Order_ProductServices = new HashSet<Order_ProductServices>();
            this.ProductServiceImages = new HashSet<ProductServiceImage>();
            this.Quote_ProductServices = new HashSet<Quote_ProductServices>();
        }
    
        public int ProductServiceId { get; set; }
        public string Description { get; set; }
        public int CatalogueId { get; set; }
        public int CompanyId { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SalesValue { get; set; }
        public int DisplayOrder { get; set; }
        public bool Deleted { get; set; }
        public bool HasImage { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_ProductServices> Order_ProductServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductServiceImage> ProductServiceImages { get; set; }
        public virtual ProductService ProductServices1 { get; set; }
        public virtual ProductService ProductService1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_ProductServices> Quote_ProductServices { get; set; }
    }
}
