//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteAddress
    {
        public int QuoteAddressId { get; set; }
        public int QuoteId { get; set; }
        public int AddressId { get; set; }
        public Nullable<int> AddressType { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AddressType AddressType1 { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
