//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.Orders = new HashSet<Order>();
            this.Quote_Colours = new HashSet<Quote_Colours>();
            this.Quote_DoorStyles = new HashSet<Quote_DoorStyles>();
            this.Quote_Products = new HashSet<Quote_Products>();
            this.Quote_ProductServices = new HashSet<Quote_ProductServices>();
            this.QuoteAddresses = new HashSet<QuoteAddress>();
        }
    
        public int QuoteId { get; set; }
        public string QuoteRef { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int CompanyId { get; set; }
        public int TrendUserId { get; set; }
        public Nullable<int> VATRateID { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> PrimaryDoorStyle { get; set; }
        public Nullable<int> DrawerBoxColour { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<decimal> NetGrossTotal { get; set; }
        public Nullable<decimal> CostVatTotal { get; set; }
        public Nullable<decimal> NetCostTotal { get; set; }
        public Nullable<decimal> SalesGrossTotal { get; set; }
        public Nullable<decimal> SalesVatTotal { get; set; }
        public Nullable<decimal> NetSalesTotal { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<int> DeliveryMethod { get; set; }
        public Nullable<System.DateTime> DeliveryDateWc { get; set; }
        public string DeliveryNotes { get; set; }
        public Nullable<int> Catalogue { get; set; }
        public Nullable<int> PrimaryCabinetColour { get; set; }
        public bool AddVAT { get; set; }
        public bool CustomerPanelVisible { get; set; }
        public bool ContactPanelVisible { get; set; }
        public Nullable<bool> UseDelivery { get; set; }
        public Nullable<int> AddressIDToUse { get; set; }
        public bool DeliveryDetailsConfirmed { get; set; }
        public bool TermsConfirmed { get; set; }
        public bool ReadOnly { get; set; }
        public Nullable<int> PrimaryHandleStyle { get; set; }
        public Nullable<decimal> CurrencySurcharge { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Catalogue Catalogue1 { get; set; }
        public virtual Colour Colour { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryMethod DeliveryMethod1 { get; set; }
        public virtual DoorStyle DoorStyle { get; set; }
        public virtual DrawerBox DrawerBox { get; set; }
        public virtual OrderQuoteStatu OrderQuoteStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Order Order { get; set; }
        public virtual PaymentMethod PaymentMethod1 { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_Colours> Quote_Colours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_DoorStyles> Quote_DoorStyles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_Products> Quote_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_ProductServices> Quote_ProductServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteAddress> QuoteAddresses { get; set; }
        public virtual TrendUser TrendUser { get; set; }
        public virtual VatRate VatRate { get; set; }
    }
}
