//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Products
    {
        public int Quote_ProductId { get; set; }
        public int ProductId { get; set; }
        public int QuoteId { get; set; }
        public Nullable<decimal> NetCostPrice { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<decimal> TotalCostPrice { get; set; }
        public Nullable<decimal> MarkUpPercent { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool UndrilledForHinges { get; set; }
        public Nullable<int> DoorHang { get; set; }
        public bool DryAssembled { get; set; }
        public Nullable<int> DoorOption { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<int> DoorStyleId { get; set; }
        public Nullable<int> CabinetColourId { get; set; }
        public Nullable<decimal> AdditionalCharges { get; set; }
        public Nullable<bool> DepthModified { get; set; }
    
        public virtual DoorHang DoorHang1 { get; set; }
        public virtual DoorOption DoorOption1 { get; set; }
        public virtual DoorStyle DoorStyle { get; set; }
        public virtual Product Product { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
