//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RangeGroup()
        {
            this.GlazedDoorStyles_RangeGroups = new HashSet<GlazedDoorStyles_RangeGroups>();
            this.RangeGroup_DoorStyle = new HashSet<RangeGroup_DoorStyle>();
            this.RangeGroup_Tags = new HashSet<RangeGroup_Tags>();
        }
    
        public int RangeGroupId { get; set; }
        public int CatalogueId { get; set; }
        public string RangeGroupName { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public int PriceGroupFilter { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<int> RangeGroup_GroupID { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlazedDoorStyles_RangeGroups> GlazedDoorStyles_RangeGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RangeGroup_DoorStyle> RangeGroup_DoorStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RangeGroup_Tags> RangeGroup_Tags { get; set; }
    }
}
