//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationaryTemplate
    {
        public int StationaryTemplateId { get; set; }
        public int CatalogueId { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public bool Deleted { get; set; }
        public int LayoutMargin { get; set; }
        public bool AddHeaderLogo { get; set; }
        public int HeaderLogoPlacement { get; set; }
        public bool AddHeaderCompanyName { get; set; }
        public int HeaderTextAlignment { get; set; }
        public bool AddHeaderCompanyAddress { get; set; }
        public int HeaderFontSize { get; set; }
        public bool AddHeaderCompanyTel { get; set; }
        public bool AddHeaderCompanyEmail { get; set; }
        public bool AddHeaderVatNo { get; set; }
        public bool AddCustomerQuoteRef { get; set; }
        public int CustomerFontSize { get; set; }
        public bool AddCustomerName { get; set; }
        public bool AddCustomerAddress { get; set; }
        public bool AddCustomerTel { get; set; }
        public bool AddCustomerMobile { get; set; }
        public bool AddQuoteLineItems { get; set; }
        public bool AddQuoteItemDetail { get; set; }
        public bool AddQuoteIndividualPrices { get; set; }
        public bool AddCategoryTotals { get; set; }
        public bool AddTotalCost { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Company Company { get; set; }
    }
}
