//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategory()
        {
            this.Product_SubCategory = new HashSet<Product_SubCategory>();
            this.SubCategoryImages = new HashSet<SubCategoryImage>();
        }
    
        public int SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ProductType { get; set; }
        public string MaxLength { get; set; }
        public bool AllowUndrilled { get; set; }
        public bool AllowDoorHang { get; set; }
        public bool AllowDryAssembled { get; set; }
        public bool AllowDoorOptions { get; set; }
        public bool AllowDoorChange { get; set; }
        public bool AllowColourChange { get; set; }
        public bool UniversallyConfigurable { get; set; }
        public string ImageSource { get; set; }
        public Nullable<bool> HasImage { get; set; }
        public Nullable<bool> DepthConfigurable { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_SubCategory> Product_SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategoryImage> SubCategoryImages { get; set; }
    }
}
