//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TenantSetting()
        {
            this.Tenant_TenantSettings = new HashSet<Tenant_TenantSettings>();
        }
    
        public int TenantSettingId { get; set; }
        public int TenantSettingCategoryId { get; set; }
        public string Description { get; set; }
        public string DefaultValue { get; set; }
        public bool DenyAccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenant_TenantSettings> Tenant_TenantSettings { get; set; }
        public virtual TenantSettingCategory TenantSettingCategory { get; set; }
    }
}
