//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantDomain
    {
        public int TenantDomainId { get; set; }
        public int TenantId { get; set; }
        public string Url { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
