//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendTestApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrendUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrendUser()
        {
            this.Orders = new HashSet<Order>();
            this.ProductFavourites = new HashSet<ProductFavourite>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public int TrendUserId { get; set; }
        public string AspNetUserId { get; set; }
        public string TokenReset { get; set; }
        public Nullable<int> TenantId { get; set; }
        public int UserTypeId { get; set; }
        public string Email { get; set; }
        public int CompanyId { get; set; }
        public string Fullname { get; set; }
        public string Notes { get; set; }
        public int IntroductionRouteId { get; set; }
        public string IntroductionRouteOther { get; set; }
        public string UserName { get; set; }
        public bool InsecurePassword { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Company Company { get; set; }
        public virtual IntroductionRoute IntroductionRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFavourite> ProductFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
